### PR TITLE
Fix #1: Get nvidia driver version while make all

### LINKED ISSUE #1: compile error, missing parameter -lnvidia-ml
i think theres a problem with your Makefile.

heres the error im getting:

g++ -I/usr/local/cuda//include -L/usr/local/cuda//lib64/ cuda-smi.cpp -lnvidia-ml -lcudart_static -lpthread -ldl -lrt -o cuda-smi
/usr/bin/ld: cannot find -lnvidia-ml
collect2: error: ld returned 1 exit status
make: **\* [cuda-smi] Fehler 1

some sys specs:

cuda toolkit version 7.0 from nvidia.com resides in /usr/local/cuda
cuda management library newest installed in global scope (as of 30-5-2015)
g++ version (Ubuntu 4.8.2-19ubuntu1) 4.8.2
sys Description: Ubuntu 14.04.2 LTS
nvidia module version: nvidia-349, 349.16, 4.0.1, x86_64: installed

hope youre able to help me out.
greetings
Oliver

### PR DESCRIPTION
**Pull request by wkentaro**
I assume the build is running on ubuntu.

### CODE REVIEW

**Comment by al42and** [comment]
Hi.

I checked, and it seems to work nice.

I've got a question, though.
Parsing `/proc/driver/nvidia/version` seems a bit convoluted.
Any reason not to do something like `modinfo -F version nvidia | sed 's/\(.*\)\.\(.*\)/\1/'`?

It seems shorter and more straightforward, and can be put right into Makefile, so we don't need to have additional file:

```
NVIDIA_DRIVER_VERSION=$(shell modinfo -F version nvidia 2>/dev/null | sed 's/\(.*\)\.\(.*\)/\1/')
```

**Comment by wkentaro** [comment]
That looks better. 
I didn't know that.

**Comment by wkentaro** [comment]
I have error on my environment. Am I missing something?

```
% modinfo -F version nvidia
modinfo: ERROR: Module nvidia not found.

% modinfo -F version nvidia_352
352.63
```

**Comment by wkentaro** [comment]
I rewrote the code without the additional file.

**Comment by al42and** [comment]
Awesome, thanks! :+1: 

> I have error on my environment. Am I missing something?
> Seems there are too many ways to package nvidia driver :)

**Pull request merged**
