### PR TITLE
Fix to build cuda-smi on macOS (without nvml)

### PR DESCRIPTION
**Pull request by wkentaro**
a

### CODE REVIEW

**Comment by al42and** [comment]
Hi Kentaro!

Thank you for your contribution!

But since I rely a lot on NVML, the resulting codes for Linux and MacOS become quite different (it looks that only 50% of code is shared between both platforms).
And since I don't have any Macs available to test any changes I might make, I don't think it's a good idea for me to maintain it.

If you wish, you can make a fork specifically for MacOS, and I will link to your project from Readme.
I think it would both ensure better maintenance and cleaner code without tons of `#ifdef`s.

P.S. It's necessary to call `cudaSetDevice(deviceId)` before using `cudaMemGetInfo`. Right now your code is always reporting memory usage of first device even if there are several GPUs in the system.

P.S.2: Why I use NVML? Well, originally this tool was made specifically to map CUDA device ids to the ones used by `nvidia smi`, so that's it.
Also, `nvmlDeviceGetMemoryInfo` seems to work faster than `cudaMemGetInfo`, since it does not initialize context on queried devices.

**Comment by wkentaro** [comment]
Splitting repository is an idea, but I think placing code for same purpose in a single repository is efficient for user to find the feature.

Actually, the conditions for MacOS are not for the OS in actual but the existence of nvml, and I think you can test the code on Ubuntu.
What about `make NO_NVML:=true`?

**Comment by wkentaro** [comment]
As for the many `#ifdef`, I think we have an option to split the code to `cuda-smi-no-nvml.cpp`.

**Comment by al42and** [comment]
> As for the many #ifdef, I think we have an option to split the code to cuda-smi-no-nvml.cpp.

I'd rather prefer splitting repositories, since in this case the only common thing would be Makefile :)

> Actually, the conditions for MacOS are not for the OS in actual but the existence of nvml, and I think 
> you can test the code on Ubuntu.
> What about make NO_NVML:=true?

Good point :+1: 

I did try to reorganize code a little in 09e6b20, so it becomes more straightforward (at least to me). Also, I had a couple issues with `NO_NVML` switch on Linux, fixed them in the same comment.
Could you please check whether it still works okay on Mac?

**Comment by wkentaro** [comment]
There are not problems aside from https://github.com/al42and/cuda-smi/pull/5.

**Comment by al42and** [comment]
The issue I have with #5 is that it breaks `make NO_NVML=1` on Linux.
I tried to make more cross-platform solution in 19a3b4d.

Could you please check whether it works on Mac?

**Comment by wkentaro** [comment]
Thanks It works.

**Comment by al42and** [comment]
:+1:

**Comment by wkentaro** [comment]
Thanks.

**Pull request merged**
